### ISSUE TITLE
Can not read RDS file

### ISSUE THREAD

**Issue by roman7011** [harphub/harpVis#12] opened 2020-07-15 12:43 UTC
Hi,

I installed a fresh harp from scratch from harphub,
then I trying to run simple R-script which reads your verification sample rds data:

`
library(harpIO)
library(harpVis)
library(harpPoint)
library(here)

shiny_plot_point_verif(here(), host='10.20.7.201', port=4799)
`

applicatiotion starts and I can connect to web service,
then I open  choose file via "Select verfication directory" and press "Load" button I got an error:

"ERROR: Can not read file"

Platform is Linux, x86_64.
R version: R version 3.4.1 (2017-06-30) -- "Single Candle"
libproj version: sci-libs/proj-6.2.1   Rel. 6.2.1, November 1st, 2019

I traced app vias "strace" utility and I'm sure that file is accessible and application
opens that file and reads at least 4kb from .rds file.

Can you please help, where a problem might be ? Maybe some R libraries are still missing ?

Console output from R-script:

$ Rscript  point_verif.R
Loading required package: ggplot2
Loading required package: shiny
Loading required package: methods
here() starts at /home/roman/harp

Listening on http://10.20.7.201:4799

![error_can_not_read_file](https://user-images.githubusercontent.com/49252234/87544641-1a38f580-c6a7-11ea-84ea-8a7c5cb1e855.jpg)

Best regards
Roman Zehnal

**Comment by andrew-MET** [comment] 2020-07-20 12:42
Can you share your whole script?

The app is designed to throw an error if it doesn't recognise the content of the file to be something it can deal with, so it's possible there's an error in the script.

**Comment by mpartio** [comment] 2020-09-11 11:23
I encountered the same problem but perhaps the root cause is different?

![Screenshot from 2020-09-11 14-17-44](https://user-images.githubusercontent.com/5736267/92920091-651e8180-f43a-11ea-8fe4-f1904188e26c.png)

I have two almost equal rds files, the only difference being that first one is done using two models (MEPS_prod & IFSENS) and second with three models (MEPS_prod, MEPS_prod_cal_, IFSENS). If these rds files are in the same directory, I cannot open the one with two models. If I remove the three-model file, the two-model file opens just fine.

Maybe you can repeat this problem by extracting the two files from this zip file and trying to open them through shiny app:

[files.zip](https://github.com/harphub/harpVis/files/5208583/files.zip)

**Comment by andrew-MET** [comment] 2020-09-11 13:58
@mpartio Your issue should be fixed by #24

**Comment by mpartio** [comment] 2020-09-14 04:44
Confirmed, thanks!

**Closed** 2020-11-20 17:52 UTC
